#################################
# TOMCAT
#################################
server:
   port: 8080
   servlet:
      context-path: "/"
#      session:
#         timeout: 1800
#         cookie:
#            domain: unicona.co.kr
#            name: SAMPLEID
#            http-only: true
#            secure: false
   tomcat:
      threads:
         max: 20
         min-spare: 10
      
#################################
# LOGGING
#################################
logging:
   pattern:
      #default log pattern
      #console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
      #custom log pattern
      #console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%4line]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){red} %m%n%wEx"
   level:
      root: info
      jdbc:
         sqlonly: info
         resultset: error
         audit: error
         sqltiming: error

env:
   dir:
      core-log: "/Users/patrick/dev/project-output/logs/core-logs"
      upload: "/Users/patrick/dev/project-output/upload"
   url-after-login: '/svc/main/index.do'